# Generated by Django 5.2 on 2025-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_pos_x_donation_pos_y_donation_pos_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pos_y',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pos_z',
        ),
        migrations.AddField(
            model_name='donation',
            name='positions',
            field=models.JSONField(default=list),
        ),
    ]
